/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./../pages/__root";
import { Route as HelloImport } from "./../pages/hello";
import { Route as AuthImport } from "./../pages/auth";
import { Route as AboutImport } from "./../pages/about";
import { Route as IndexImport } from "./../pages/index";

// Create Virtual Routes

const FaqLazyImport = createFileRoute("/faq")();

// Create/Update Routes

const FaqLazyRoute = FaqLazyImport.update({
  path: "/faq",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./../pages/faq.lazy").then((d) => d.Route));

const HelloRoute = HelloImport.update({
  path: "/hello",
  getParentRoute: () => rootRoute,
} as any);

const AuthRoute = AuthImport.update({
  path: "/auth",
  getParentRoute: () => rootRoute,
} as any);

const AboutRoute = AboutImport.update({
  path: "/about",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/about": {
      preLoaderRoute: typeof AboutImport;
      parentRoute: typeof rootRoute;
    };
    "/auth": {
      preLoaderRoute: typeof AuthImport;
      parentRoute: typeof rootRoute;
    };
    "/hello": {
      preLoaderRoute: typeof HelloImport;
      parentRoute: typeof rootRoute;
    };
    "/faq": {
      preLoaderRoute: typeof FaqLazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutRoute,
  AuthRoute,
  HelloRoute,
  FaqLazyRoute,
]);

/* prettier-ignore-end */
