/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./../pages/__root"
import { Route as AuthImport } from "./../pages/auth"
import { Route as AboutImport } from "./../pages/about"
import { Route as IndexImport } from "./../pages/index"
import { Route as AboutTest8Import } from "./../pages/about.test8"

// Create/Update Routes

const AuthRoute = AuthImport.update({
  path: "/auth",
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: "/about",
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

const AboutTest8Route = AboutTest8Import.update({
  path: "/test8",
  getParentRoute: () => AboutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/about": {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    "/auth": {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    "/about/test8": {
      preLoaderRoute: typeof AboutTest8Import
      parentRoute: typeof AboutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutRoute.addChildren([AboutTest8Route]),
  AuthRoute,
])

/* prettier-ignore-end */
